import tsParser from "@typescript-eslint/parser";
import i18next from "eslint-plugin-i18next";

// Biome (via Ultracite) is the primary linter + formatter for this repo. ESLint
// is kept ONLY for `i18next/no-literal-string`, which catches untranslated
// literal strings in JSX — Biome has no equivalent rule, and this app is heavily
// localized (20 locales). Everything Biome covers (type-safety, style, a11y,
// correctness) has been removed from here; see biome.jsonc.

// react-doctor runs as a SEPARATE linter (`npx react-doctor`) with its own
// `react-doctor/*` and `react-hooks-js/*` plugins. Source carries inline
// `eslint-disable react-doctor/… | react-hooks-js/…` directives for that pass.
// Those plugins are not loaded in THIS ESLint, so each directive would otherwise
// be flagged "Definition for rule not found". Register them as no-op plugins (the
// Proxy resolves any rule name to an empty rule) so the directives resolve here
// without affecting what this ESLint actually checks; the real enforcement stays
// in react-doctor.
const noopRule = { create: () => ({}) };
const reactDoctorCompatPlugin = {
	rules: new Proxy({}, { get: () => noopRule, has: () => true }),
};

const testSourceFiles = [
	"src/**/*.{test,spec}.{ts,tsx}",
	"src/**/*test-helpers*.{ts,tsx}",
];

export default [
	{
		files: ["src/**/*.{ts,tsx}"],
		plugins: {
			"react-doctor": reactDoctorCompatPlugin,
			"react-hooks-js": reactDoctorCompatPlugin,
		},
		// The compat plugins above are no-ops in THIS ESLint, so it would otherwise
		// flag every react-doctor directive as an "unused disable directive". Those
		// directives ARE used — by react-doctor's separate pass — so don't report
		// them as unused here.
		linterOptions: { reportUnusedDisableDirectives: "off" },
	},
	{
		// The i18next plugin needs a TS/TSX-aware parser; @typescript-eslint/parser
		// is retained for that alone (its lint rules moved to Biome).
		files: ["src/**/*.{ts,tsx}"],
		languageOptions: {
			parser: tsParser,
			parserOptions: {
				ecmaFeatures: {
					jsx: true,
				},
			},
		},
		plugins: {
			i18next,
		},
		rules: {
			// Catch text in JSX that should be translated.
			"i18next/no-literal-string": [
				"error",
				{
					markupOnly: true, // Only check JSX content, not all strings
					ignoreAttribute: [
						"className",
						"style",
						"type",
						"id",
						"name",
						"key",
						"data-*",
						"aria-*",
					], // Ignore common non-translatable attributes
				},
			],
		},
	},
	{
		// Test code legitimately uses literal strings (fixtures, assertions, mock
		// data); the i18n rule is for user-facing JSX only, so turn it off here.
		files: testSourceFiles,
		plugins: { i18next },
		rules: {
			"i18next/no-literal-string": "off",
		},
	},
	{
		// Generated by tauri-specta (`cargo test export_bindings`); not
		// hand-authored, so exempt it from the i18n rule.
		files: ["src/bindings.ts"],
		plugins: { i18next },
		rules: {
			"i18next/no-literal-string": "off",
		},
	},
];
