import i18next from "eslint-plugin-i18next";
import tsParser from "@typescript-eslint/parser";
import tseslint from "@typescript-eslint/eslint-plugin";

const typeCheckedSourceFiles = ["src/**/*.{ts,tsx}", "packages/model-picker/src/**/*.{ts,tsx}"];
const testSourceFiles = [
  "src/**/*.{test,spec}.{ts,tsx}",
  "src/**/*test-helpers*.{ts,tsx}",
  "packages/model-picker/src/**/*.{test,spec}.{ts,tsx}",
  "packages/model-picker/src/**/*test-helpers*.{ts,tsx}",
];

export default [
  {
    files: typeCheckedSourceFiles,
    languageOptions: {
      parser: tsParser,
      parserOptions: {
        ecmaFeatures: {
          jsx: true,
        },
      },
    },
    plugins: {
      i18next,
      "@typescript-eslint": tseslint,
    },
    rules: {
      // Type-safety gate (syntactic rules — no type-aware parsing needed).
      // switch-exhaustiveness-check + no-floating-promises additionally require
      // parserOptions.project (type-aware, much slower) — tracked as a follow-up.
      "@typescript-eslint/no-explicit-any": "error",
      "@typescript-eslint/no-non-null-assertion": "error",
    },
  },
  {
    files: ["src/**/*.{ts,tsx}"],
    plugins: {
      i18next,
    },
    rules: {
      // Catch text in JSX that should be translated
      "i18next/no-literal-string": [
        "error",
        {
          markupOnly: true, // Only check JSX content, not all strings
          ignoreAttribute: [
            "className",
            "style",
            "type",
            "id",
            "name",
            "key",
            "data-*",
            "aria-*",
          ], // Ignore common non-translatable attributes
        },
      ],
    },
  },
  {
    // Test code legitimately uses literal strings (fixtures, assertions, mock data);
    // the i18n rule is for user-facing JSX only, so turn it off for test files.
    files: testSourceFiles,
    plugins: { i18next, "@typescript-eslint": tseslint },
    rules: {
      "i18next/no-literal-string": "off",
      // Tests legitimately assert non-null on values they construct/know-present.
      "@typescript-eslint/no-non-null-assertion": "off",
    },
  },
  {
    // Generated by tauri-specta (`cargo test export_bindings`); not hand-authored,
    // so exempt it from the type-safety + i18n rules rather than editing generated output.
    files: ["src/bindings.ts"],
    plugins: { i18next, "@typescript-eslint": tseslint },
    rules: {
      "@typescript-eslint/no-explicit-any": "off",
      "@typescript-eslint/no-non-null-assertion": "off",
      "i18next/no-literal-string": "off",
    },
  },
];
