import type { components } from "@spec/schema";

export type AudioDevice = components["schemas"]["AudioDevice"];
export type GpuInfo = components["schemas"]["GpuInfo"];
export type ServerStatus = components["schemas"]["ServerStatus"];
export type AllowedParameter = components["schemas"]["AllowedParameter"];
export type AllowedMethod = components["schemas"]["AllowedMethod"];
export type AppSettingsSaveInput = components["schemas"]["AppSettings"];
export type OllamaModel = components["schemas"]["OllamaModel"];
export type OllamaScanResult = components["schemas"]["OllamaScanResult"];
export type OllamaDetectResult = components["schemas"]["OllamaDetectResult"];
export type OllamaPullProgress = components["schemas"]["OllamaPullProgress"];
export type OllamaPullProgressStatus = components["schemas"]["OllamaPullProgressStatus"];
export type OllamaPullResult = components["schemas"]["OllamaPullResult"];
export type OllamaDeleteResult = components["schemas"]["OllamaDeleteResult"];
export type RecommendedOllamaModel = components["schemas"]["RecommendedOllamaModel"];
export type OpenRouterModel = components["schemas"]["OpenRouterModel"];
export type OpenRouterEndpoint = components["schemas"]["OpenRouterEndpoint"];
export type OpenRouterPricing = components["schemas"]["OpenRouterPricing"];
export type OpenRouterScanResult = components["schemas"]["OpenRouterScanResult"];
