"""Per-user catalog overlay — runtime cache of HF-derived editorial fields.

The bundled :file:`catalog.json` ships a static snapshot of model metadata
generated by ``scripts/refresh_catalog.py`` at release time. Once installed,
that file lives inside the PyInstaller bundle and is effectively read-only.

This module provides a writable side-channel: a JSON file in the user's home
directory that the runtime catalog refresher (see :mod:`catalog_refresh` and
the server bootstrap) writes after fetching fresh HuggingFace metadata.
:class:`ModelCatalog` applies the overlay over the bundled entries at
construction time, so the next ``stt-server`` launch starts with whatever
data the last successful refresh produced — and the dropdown stays correct
even when the user is offline at startup.

Only HF-derivable fields belong in the overlay (currently ``languages``).
Editorial fields like ``display_name`` / ``description`` / ``family`` stay
in the bundled JSON and are never overlaid.
"""

from __future__ import annotations

import json
import os
import tempfile
from pathlib import Path
from typing import Any

#: Per-user overlay path. Mirrors the convention in ``stt_server/cli.py`` which
#: persists ``server-settings.json`` to the same directory.
OVERLAY_DIR: Path = Path.home() / ".winstt"
OVERLAY_PATH: Path = OVERLAY_DIR / "catalog-overlay.json"


def load_overlay() -> dict[str, dict[str, Any]]:
    """Return the overlay mapping ``{model_id: {field: value}}``.

    Empty dict when the file doesn't exist or fails to parse — the bundled
    catalog is always a valid fallback, so a corrupt overlay must never
    propagate as an exception to the startup path.
    """
    if not OVERLAY_PATH.exists():
        return {}
    try:
        payload = json.loads(OVERLAY_PATH.read_text(encoding="utf-8"))
    except (json.JSONDecodeError, OSError):
        return {}
    if not isinstance(payload, dict):
        return {}
    overlay: dict[str, dict[str, Any]] = {}
    for model_id, fields in payload.items():
        if isinstance(model_id, str) and isinstance(fields, dict):
            overlay[model_id] = dict(fields)
    return overlay


def save_overlay(overlay: dict[str, dict[str, Any]]) -> bool:
    """Atomically write ``overlay`` to :data:`OVERLAY_PATH`. Returns success.

    Atomic rename so a crashed write never leaves a half-truncated file in
    place. Best-effort: returns ``False`` (does NOT raise) on any I/O
    error, because failing to persist the overlay is non-fatal — the next
    run just re-fetches.
    """
    try:
        OVERLAY_DIR.mkdir(parents=True, exist_ok=True)
        serialized = json.dumps(overlay, indent=2, ensure_ascii=False, sort_keys=True)
        with tempfile.NamedTemporaryFile(
            mode="w",
            encoding="utf-8",
            dir=str(OVERLAY_DIR),
            prefix=".catalog-overlay.",
            suffix=".tmp",
            delete=False,
        ) as tmp:
            tmp.write(serialized)
            tmp_path = Path(tmp.name)
        os.replace(tmp_path, OVERLAY_PATH)
        return True
    except OSError:  # pragma: no cover - disk-full / permissions; non-fatal by design
        return False
