"""Per-user catalog overlay — runtime cache of HF-derived editorial fields.

The bundled :file:`catalog.json` ships a static snapshot of model metadata
generated by ``scripts/refresh_catalog.py`` at release time. Once installed,
that file lives inside the PyInstaller bundle and is effectively read-only.

This module provides a writable side-channel: a JSON file in the user's home
directory that the runtime catalog refresher (see :mod:`catalog_refresh` and
the server bootstrap) writes after fetching fresh HuggingFace metadata.
:class:`ModelCatalog` applies the overlay over the bundled entries at
construction time, so the next ``stt-server`` launch starts with whatever
data the last successful refresh produced — and the dropdown stays correct
even when the user is offline at startup.

Only HF-derivable fields belong in the overlay (currently ``languages``).
Editorial fields like ``display_name`` / ``description`` / ``family`` stay
in the bundled JSON and are never overlaid.
"""

from __future__ import annotations

import json
import os
import tempfile
from pathlib import Path
from typing import TYPE_CHECKING, Any, cast

if TYPE_CHECKING:
    from collections.abc import Iterator

#: Per-user overlay path. Mirrors the convention in ``stt_server/cli.py`` which
#: persists ``server-settings.json`` to the same directory.
OVERLAY_DIR: Path = Path.home() / ".winstt"
OVERLAY_PATH: Path = OVERLAY_DIR / "catalog-overlay.json"


def _read_overlay_payload() -> object | None:
    """Parse the overlay file, returning ``None`` on absence / corruption."""
    if not OVERLAY_PATH.exists():
        return None
    try:
        parsed: object = json.loads(OVERLAY_PATH.read_text(encoding="utf-8"))
    except (json.JSONDecodeError, OSError):
        return None
    return parsed


def _is_str_dict_pair(pair: tuple[object, object]) -> bool:
    model_id, fields = pair
    return isinstance(model_id, str) and isinstance(fields, dict)


def _str_dict_pairs(payload: dict[object, object]) -> Iterator[tuple[str, dict[str, Any]]]:
    """Yield only the ``(str, dict)`` entries of a parsed overlay payload."""
    for pair in payload.items():
        if _is_str_dict_pair(pair):
            yield cast("tuple[str, dict[str, Any]]", pair)


def _coerce_overlay(payload: object | None) -> dict[str, dict[str, Any]]:
    """Keep only ``{str: dict}`` entries from a parsed overlay payload."""
    if not isinstance(payload, dict):
        return {}
    return {model_id: dict(fields) for model_id, fields in _str_dict_pairs(payload)}


def load_overlay() -> dict[str, dict[str, Any]]:
    """Return the overlay mapping ``{model_id: {field: value}}``.

    Empty dict when the file doesn't exist or fails to parse — the bundled
    catalog is always a valid fallback, so a corrupt overlay must never
    propagate as an exception to the startup path.
    """
    return _coerce_overlay(_read_overlay_payload())


def save_overlay(overlay: dict[str, dict[str, Any]]) -> bool:
    """Atomically write ``overlay`` to :data:`OVERLAY_PATH`. Returns success.

    Atomic rename so a crashed write never leaves a half-truncated file in
    place. Best-effort: returns ``False`` (does NOT raise) on any I/O
    error, because failing to persist the overlay is non-fatal — the next
    run just re-fetches.
    """
    try:
        OVERLAY_DIR.mkdir(parents=True, exist_ok=True)
        serialized = json.dumps(overlay, indent=2, ensure_ascii=False, sort_keys=True)
        with tempfile.NamedTemporaryFile(
            mode="w",
            encoding="utf-8",
            dir=str(OVERLAY_DIR),
            prefix=".catalog-overlay.",
            suffix=".tmp",
            delete=False,
        ) as tmp:
            tmp.write(serialized)
            tmp_path = Path(tmp.name)
        os.replace(tmp_path, OVERLAY_PATH)
        return True
    except OSError:  # pragma: no cover - disk-full / permissions; non-fatal by design
        return False
