import type { components } from "@spec/schema";

export const WHISPER_MODELS = [
	"tiny",
	"tiny.en",
	"base",
	"base.en",
	"small",
	"small.en",
	"medium",
	"medium.en",
	"large-v1",
	"large-v2",
	"large-v3",
	"large-v3-turbo",
] as const satisfies readonly components["schemas"]["WhisperModel"][];

export const COMPUTE_TYPES = [
	"default",
	"auto",
	"int8",
	"int8_float16",
	"int8_float32",
	"int8_bfloat16",
	"int16",
	"float16",
	"float32",
	"bfloat16",
] as const satisfies readonly components["schemas"]["ComputeType"][];

// onnx-asr quantization tier — the suffix it adds to the model filename
// when resolving HF assets (e.g. ``encoder_model_int8.onnx``). Different
// models ship different variants; "" means "default file" (typically fp32)
// and is the safest pick. ``onnx_quantization`` is a free-form string on
// the server, so we keep this list to a conservative cross-model subset
// rather than enumerating every variant any one repo might publish.
export const ONNX_QUANTIZATIONS = [
	"", // default / fp32 — always present
	"int8",
	"fp16",
	"uint8",
	"q4",
	"q4f16",
	"bnb4",
] as const;
export type OnnxQuantization = (typeof ONNX_QUANTIZATIONS)[number];

export const LANGUAGES: readonly { code: string; name: string }[] = [
	{ code: "", name: "Auto-detect" },
	{ code: "af", name: "Afrikaans" },
	{ code: "am", name: "Amharic" },
	{ code: "ar", name: "Arabic" },
	{ code: "as", name: "Assamese" },
	{ code: "az", name: "Azerbaijani" },
	{ code: "ba", name: "Bashkir" },
	{ code: "be", name: "Belarusian" },
	{ code: "bg", name: "Bulgarian" },
	{ code: "bn", name: "Bengali" },
	{ code: "bo", name: "Tibetan" },
	{ code: "br", name: "Breton" },
	{ code: "bs", name: "Bosnian" },
	{ code: "ca", name: "Catalan" },
	{ code: "cs", name: "Czech" },
	{ code: "cy", name: "Welsh" },
	{ code: "da", name: "Danish" },
	{ code: "de", name: "German" },
	{ code: "el", name: "Greek" },
	{ code: "en", name: "English" },
	{ code: "es", name: "Spanish" },
	{ code: "et", name: "Estonian" },
	{ code: "eu", name: "Basque" },
	{ code: "fa", name: "Persian" },
	{ code: "fi", name: "Finnish" },
	{ code: "fo", name: "Faroese" },
	{ code: "fr", name: "French" },
	{ code: "gl", name: "Galician" },
	{ code: "gu", name: "Gujarati" },
	{ code: "ha", name: "Hausa" },
	{ code: "haw", name: "Hawaiian" },
	{ code: "he", name: "Hebrew" },
	{ code: "hi", name: "Hindi" },
	{ code: "hr", name: "Croatian" },
	{ code: "ht", name: "Haitian Creole" },
	{ code: "hu", name: "Hungarian" },
	{ code: "hy", name: "Armenian" },
	{ code: "id", name: "Indonesian" },
	{ code: "is", name: "Icelandic" },
	{ code: "it", name: "Italian" },
	{ code: "ja", name: "Japanese" },
	{ code: "jw", name: "Javanese" },
	{ code: "ka", name: "Georgian" },
	{ code: "kk", name: "Kazakh" },
	{ code: "km", name: "Khmer" },
	{ code: "kn", name: "Kannada" },
	{ code: "ko", name: "Korean" },
	{ code: "la", name: "Latin" },
	{ code: "lb", name: "Luxembourgish" },
	{ code: "ln", name: "Lingala" },
	{ code: "lo", name: "Lao" },
	{ code: "lt", name: "Lithuanian" },
	{ code: "lv", name: "Latvian" },
	{ code: "mg", name: "Malagasy" },
	{ code: "mi", name: "Maori" },
	{ code: "mk", name: "Macedonian" },
	{ code: "ml", name: "Malayalam" },
	{ code: "mn", name: "Mongolian" },
	{ code: "mr", name: "Marathi" },
	{ code: "ms", name: "Malay" },
	{ code: "mt", name: "Maltese" },
	{ code: "my", name: "Myanmar" },
	{ code: "ne", name: "Nepali" },
	{ code: "nl", name: "Dutch" },
	{ code: "nn", name: "Nynorsk" },
	{ code: "no", name: "Norwegian" },
	{ code: "oc", name: "Occitan" },
	{ code: "pa", name: "Panjabi" },
	{ code: "pl", name: "Polish" },
	{ code: "ps", name: "Pashto" },
	{ code: "pt", name: "Portuguese" },
	{ code: "ro", name: "Romanian" },
	{ code: "ru", name: "Russian" },
	{ code: "sa", name: "Sanskrit" },
	{ code: "sd", name: "Sindhi" },
	{ code: "si", name: "Sinhala" },
	{ code: "sk", name: "Slovak" },
	{ code: "sl", name: "Slovenian" },
	{ code: "sn", name: "Shona" },
	{ code: "so", name: "Somali" },
	{ code: "sq", name: "Albanian" },
	{ code: "sr", name: "Serbian" },
	{ code: "su", name: "Sundanese" },
	{ code: "sv", name: "Swedish" },
	{ code: "sw", name: "Swahili" },
	{ code: "ta", name: "Tamil" },
	{ code: "te", name: "Telugu" },
	{ code: "tg", name: "Tajik" },
	{ code: "th", name: "Thai" },
	{ code: "tk", name: "Turkmen" },
	{ code: "tl", name: "Tagalog" },
	{ code: "tr", name: "Turkish" },
	{ code: "tt", name: "Tatar" },
	{ code: "uk", name: "Ukrainian" },
	{ code: "ur", name: "Urdu" },
	{ code: "uz", name: "Uzbek" },
	{ code: "vi", name: "Vietnamese" },
	{ code: "yi", name: "Yiddish" },
	{ code: "yo", name: "Yoruba" },
	{ code: "yue", name: "Cantonese" },
	{ code: "zh", name: "Chinese" },
] as const;

export const DEFAULT_HOTKEY = "LCtrl+LMeta";

export const STT_CONTROL_PORT = 8011;
export const STT_DATA_PORT = 8012;
