// The static STT catalog: the `ModelEntry` row shape + the verbatim 73-row `STT_CATALOG`
// const ported from `catalog.json`. Pure data, no policy. The precision/EP resolution policy
// that consumes these rows lives in the sibling `policy` module.

use super::policy::Family;

/// One catalog row. The Rust analogue of WinSTT's `ModelInfo` (the slice subset the engine +
/// picker policy actually need; editorial fields like `wer`/`rtfx`/`size_bytes_by_quantization`
/// live in the picker payload and are intentionally NOT modeled here to keep this table a
/// load-bearing engine table rather than a UI mirror).
#[derive(Debug, Clone, Copy)]
pub struct ModelEntry {
    /// Stable catalog id (e.g. `"tiny"`, `"nemo-canary-1b-v2"`, `"alphacep/vosk-model-ru"`).
    pub id: &'static str,
    /// Human-facing label.
    pub display_name: &'static str,
    pub family: Family,
    /// HuggingFace repo id OR a bare onnx-asr alias (Moonshine/NeMo/GigaAM/etc. use aliases;
    /// Whisper/Cohere/SenseVoice/Kaldi-Vosk use slashed HF repos). The onnx-asr resolver is the
    /// single source of truth for which files this maps to.
    pub onnx_model_name: &'static str,
    /// ONNX quantization suffixes the upstream repo actually ships. The empty string `""` is the
    /// default (un-suffixed fp32) export. Order is preserved from `catalog.json`.
    pub available_quantizations: &'static [&'static str],
    /// Approximate parameter count. Drives the fp16-auto threshold (>= 500M) and the
    /// hardware-fitness estimate. `0` means "unknown" (custom models).
    pub param_count: u64,
    /// `true` for every shipped catalog entry today (kept per-row so it can diverge later).
    pub supports_realtime: bool,
}

/// The full STT catalog: 73 shipped models. Verbatim from `catalog.json` (id / display_name /
/// family / onnx_model_name / available_quantizations / param_count / supports_realtime).
///
/// Counts (asserted in tests): whisper 15, moonshine 10, nemo 34, kaldi 4, gigaam 2,
/// cohere 1, granite 2, sense_voice 1, t-one 1, dolphin 1, qwen3 2.
pub const STT_CATALOG: &[ModelEntry] = &[
    // ── Whisper family (15) ──────────────────────────────────────────────────────────────
    ModelEntry {
        id: "tiny",
        display_name: "Whisper Tiny",
        family: Family::Whisper,
        onnx_model_name: "onnx-community/whisper-tiny",
        available_quantizations: &["", "fp16", "q4", "bnb4"],
        param_count: 37_760_640,
        supports_realtime: true,
    },
    ModelEntry {
        id: "base",
        display_name: "Whisper Base",
        family: Family::Whisper,
        onnx_model_name: "onnx-community/whisper-base",
        available_quantizations: &["", "fp16", "q4", "bnb4"],
        param_count: 72_593_920,
        supports_realtime: true,
    },
    ModelEntry {
        id: "small",
        display_name: "Whisper Small",
        family: Family::Whisper,
        onnx_model_name: "onnx-community/whisper-small",
        available_quantizations: &["", "fp16", "q4", "bnb4"],
        param_count: 241_734_912,
        supports_realtime: true,
    },
    ModelEntry {
        id: "medium",
        display_name: "Whisper Medium",
        family: Family::Whisper,
        onnx_model_name: "Xenova/whisper-medium",
        available_quantizations: &["", "fp16", "q4", "bnb4"],
        param_count: 769_000_000,
        supports_realtime: true,
    },
    ModelEntry {
        id: "large-v3",
        display_name: "Whisper Large v3",
        family: Family::Whisper,
        onnx_model_name: "Xenova/whisper-large-v3",
        available_quantizations: &[""],
        param_count: 1_550_000_000,
        supports_realtime: true,
    },
    ModelEntry {
        id: "large-v3-turbo",
        display_name: "Whisper Large v3 Turbo",
        family: Family::Whisper,
        onnx_model_name: "onnx-community/whisper-large-v3-turbo",
        available_quantizations: &["", "fp16", "q4", "bnb4"],
        param_count: 795_766_657,
        supports_realtime: true,
    },
    ModelEntry {
        id: "tiny.en",
        display_name: "Whisper Tiny (EN)",
        family: Family::Whisper,
        onnx_model_name: "onnx-community/whisper-tiny.en",
        available_quantizations: &["", "fp16", "q4", "bnb4"],
        param_count: 37_760_256,
        supports_realtime: true,
    },
    ModelEntry {
        id: "base.en",
        display_name: "Whisper Base (EN)",
        family: Family::Whisper,
        onnx_model_name: "onnx-community/whisper-base.en",
        available_quantizations: &["", "fp16", "q4", "bnb4"],
        param_count: 74_000_000,
        supports_realtime: true,
    },
    ModelEntry {
        id: "small.en",
        display_name: "Whisper Small (EN)",
        family: Family::Whisper,
        onnx_model_name: "onnx-community/whisper-small.en",
        available_quantizations: &["", "fp16", "q4", "bnb4"],
        param_count: 244_000_000,
        supports_realtime: true,
    },
    ModelEntry {
        id: "medium.en",
        display_name: "Whisper Medium (EN)",
        family: Family::Whisper,
        onnx_model_name: "Xenova/whisper-medium.en",
        available_quantizations: &["", "fp16", "q4", "bnb4"],
        param_count: 769_000_000,
        supports_realtime: true,
    },
    ModelEntry {
        id: "breeze-asr-25",
        display_name: "Breeze ASR 25",
        family: Family::Whisper,
        onnx_model_name: "xeonchen/Breeze-ASR-25-ONNX",
        available_quantizations: &[""],
        param_count: 1_545_107_214,
        supports_realtime: true,
    },
    ModelEntry {
        id: "crisper-whisper",
        display_name: "CrisperWhisper",
        family: Family::Whisper,
        onnx_model_name: "onnx-community/CrisperWhisper-ONNX",
        available_quantizations: &[""],
        param_count: 1_543_304_960,
        supports_realtime: true,
    },
    ModelEntry {
        id: "lite-whisper-large-v3-turbo",
        display_name: "Lite-Whisper Large v3 Turbo",
        family: Family::Whisper,
        onnx_model_name: "onnx-community/lite-whisper-large-v3-turbo-ONNX",
        available_quantizations: &["", "fp16"],
        param_count: 534_359_083,
        supports_realtime: true,
    },
    ModelEntry {
        id: "lite-whisper-large-v3-turbo-acc",
        display_name: "Lite-Whisper Large v3 Turbo (Accelerated)",
        family: Family::Whisper,
        onnx_model_name: "onnx-community/lite-whisper-large-v3-turbo-acc-ONNX",
        available_quantizations: &["", "fp16"],
        param_count: 581_299_243,
        supports_realtime: true,
    },
    ModelEntry {
        id: "lite-whisper-large-v3-turbo-fast",
        display_name: "Lite-Whisper Large v3 Turbo (Fast)",
        family: Family::Whisper,
        onnx_model_name: "onnx-community/lite-whisper-large-v3-turbo-fast-ONNX",
        available_quantizations: &["", "fp16"],
        param_count: 473_840_689,
        supports_realtime: true,
    },
    // ── Moonshine family (10) ────────────────────────────────────────────────────────────
    ModelEntry {
        id: "moonshine-tiny",
        display_name: "Moonshine Tiny",
        family: Family::Moonshine,
        onnx_model_name: "moonshine-tiny",
        available_quantizations: &["", "fp16", "q4", "bnb4", "int8", "uint8", "q4f16"],
        param_count: 27_092_835,
        supports_realtime: true,
    },
    ModelEntry {
        id: "moonshine-base",
        display_name: "Moonshine Base",
        family: Family::Moonshine,
        onnx_model_name: "moonshine-base",
        available_quantizations: &["", "fp16", "q4", "bnb4", "int8", "uint8", "q4f16"],
        param_count: 61_514_019,
        supports_realtime: true,
    },
    ModelEntry {
        id: "moonshine-tiny-ko",
        display_name: "Moonshine Tiny (KO)",
        family: Family::Moonshine,
        onnx_model_name: "moonshine-tiny-ko",
        available_quantizations: &["", "fp16", "q4", "bnb4", "int8", "uint8", "q4f16"],
        param_count: 27_092_835,
        supports_realtime: true,
    },
    ModelEntry {
        id: "moonshine-tiny-ar",
        display_name: "Moonshine Tiny (AR)",
        family: Family::Moonshine,
        onnx_model_name: "moonshine-tiny-ar",
        available_quantizations: &["", "fp16", "q4", "bnb4", "int8", "uint8", "q4f16"],
        param_count: 27_092_835,
        supports_realtime: true,
    },
    ModelEntry {
        id: "moonshine-tiny-vi",
        display_name: "Moonshine Tiny (VI)",
        family: Family::Moonshine,
        onnx_model_name: "moonshine-tiny-vi",
        available_quantizations: &["", "fp16", "q4", "bnb4", "int8", "uint8", "q4f16"],
        param_count: 27_092_835,
        supports_realtime: true,
    },
    ModelEntry {
        id: "moonshine-base-zh",
        display_name: "Moonshine Base (ZH)",
        family: Family::Moonshine,
        onnx_model_name: "moonshine-base-zh",
        available_quantizations: &["", "fp16", "q4", "bnb4", "int8", "uint8", "q4f16"],
        param_count: 61_514_019,
        supports_realtime: true,
    },
    ModelEntry {
        id: "moonshine-base-ja",
        display_name: "Moonshine Base (JA)",
        family: Family::Moonshine,
        onnx_model_name: "moonshine-base-ja",
        available_quantizations: &["", "fp16", "q4", "bnb4", "int8", "uint8", "q4f16"],
        param_count: 61_514_019,
        supports_realtime: true,
    },
    ModelEntry {
        id: "moonshine-base-ko",
        display_name: "Moonshine Base (KO)",
        family: Family::Moonshine,
        onnx_model_name: "moonshine-base-ko",
        available_quantizations: &["", "fp16", "q4", "bnb4", "int8", "uint8", "q4f16"],
        param_count: 61_514_019,
        supports_realtime: true,
    },
    ModelEntry {
        id: "moonshine-tiny-uk",
        display_name: "Moonshine Tiny (UK)",
        family: Family::Moonshine,
        onnx_model_name: "moonshine-tiny-uk",
        available_quantizations: &[""],
        param_count: 27_600_000,
        supports_realtime: true,
    },
    ModelEntry {
        id: "moonshine-tiny-fr",
        display_name: "Moonshine Tiny (FR)",
        family: Family::Moonshine,
        onnx_model_name: "moonshine-tiny-fr",
        available_quantizations: &[""],
        param_count: 27_600_000,
        supports_realtime: true,
    },
    // ── Cohere family (1) ────────────────────────────────────────────────────────────────
    ModelEntry {
        id: "cohere-transcribe",
        display_name: "Cohere Transcribe",
        family: Family::Cohere,
        onnx_model_name: "cohere-transcribe",
        available_quantizations: &["", "fp16", "q4", "q4f16"],
        param_count: 2_000_000_000,
        supports_realtime: true,
    },
    // ── Granite family (2) ───────────────────────────────────────────────────────────────
    ModelEntry {
        id: "granite-speech-4.1-2b-plus",
        display_name: "Granite Speech 4.1 2B Plus",
        family: Family::Granite,
        onnx_model_name: "smcleod/ibm-granite-speech-4.1-2b-plus-onnx",
        available_quantizations: &["", "int8", "fp16w"],
        param_count: 2_000_000_000,
        supports_realtime: true,
    },
    ModelEntry {
        id: "granite-speech-4.1-2b-nar",
        display_name: "Granite Speech 4.1 2B NAR",
        family: Family::Granite,
        onnx_model_name: "smcleod/ibm-granite-speech-4.1-2b-nar-onnx",
        available_quantizations: &["", "int8", "fp16w"],
        param_count: 2_000_000_000,
        supports_realtime: true,
    },
    // ── Qwen3-ASR family (2) ─────────────────────────────────────────────────────────────
    // Qwen3 LLM decoder + Whisper-style audio encoder. The fp default export is 4–10 GB, so only
    // the int4 weight-quantized variant (`*.int4.onnx` + `decoder_weights.int4.data`) is shipped.
    ModelEntry {
        id: "qwen3-asr-0.6b",
        display_name: "Qwen3-ASR 0.6B",
        family: Family::Qwen3,
        onnx_model_name: "andrewleech/qwen3-asr-0.6b-onnx",
        available_quantizations: &["int4"],
        param_count: 600_000_000,
        supports_realtime: true,
    },
    ModelEntry {
        id: "qwen3-asr-1.7b",
        display_name: "Qwen3-ASR 1.7B",
        family: Family::Qwen3,
        onnx_model_name: "andrewleech/qwen3-asr-1.7b-onnx",
        available_quantizations: &["int4"],
        param_count: 1_700_000_000,
        supports_realtime: true,
    },
    // ── SenseVoice family (1) ────────────────────────────────────────────────────────────
    ModelEntry {
        id: "sense-voice-small",
        display_name: "SenseVoice Small",
        family: Family::SenseVoice,
        onnx_model_name: "csukuangfj/sherpa-onnx-sense-voice-zh-en-ja-ko-yue-2024-07-17",
        available_quantizations: &["int8"],
        param_count: 234_000_000,
        supports_realtime: true,
    },
    // ── NeMo family + native streaming rows ───────────────────────────────────────────────
    ModelEntry {
        id: "nemo-parakeet-ctc-0.6b",
        display_name: "NeMo Parakeet CTC 0.6B",
        family: Family::Nemo,
        onnx_model_name: "nemo-parakeet-ctc-0.6b",
        available_quantizations: &["", "int8"],
        param_count: 600_000_000,
        supports_realtime: true,
    },
    ModelEntry {
        id: "nemo-parakeet-rnnt-0.6b",
        display_name: "NeMo Parakeet RNNT 0.6B",
        family: Family::Nemo,
        onnx_model_name: "nemo-parakeet-rnnt-0.6b",
        available_quantizations: &["", "int8"],
        param_count: 600_000_000,
        supports_realtime: true,
    },
    ModelEntry {
        id: "nemo-parakeet-tdt-0.6b-v3",
        display_name: "NeMo Parakeet TDT 0.6B v3",
        family: Family::Nemo,
        onnx_model_name: "nemo-parakeet-tdt-0.6b-v3",
        available_quantizations: &["", "int8"],
        param_count: 626_983_558,
        supports_realtime: true,
    },
    ModelEntry {
        id: "nemo-canary-1b-v2",
        display_name: "NeMo Canary 1B v2",
        family: Family::Nemo,
        onnx_model_name: "nemo-canary-1b-v2",
        available_quantizations: &["", "int8"],
        param_count: 978_000_000,
        supports_realtime: true,
    },
    // ── Native streaming (sherpa-format exports on WinSTT ORT; cache-aware chunked). The id contains
    //    "streaming" so `engine_kind_for` routes to the *Streaming EngineKind. ──
    ModelEntry {
        id: "streaming-zipformer-en",
        display_name: "Streaming Zipformer (English)",
        family: Family::Kaldi,
        onnx_model_name: "csukuangfj/sherpa-onnx-streaming-zipformer-en-2023-06-26",
        available_quantizations: &["", "int8"],
        param_count: 66_000_000,
        supports_realtime: true,
    },
    ModelEntry {
        id: "streaming-nemo-ctc-en",
        display_name: "Streaming NeMo FastConformer CTC 80ms (English)",
        family: Family::Nemo,
        onnx_model_name: "csukuangfj/sherpa-onnx-nemo-streaming-fast-conformer-ctc-en-80ms",
        available_quantizations: &[""],
        param_count: 114_000_000,
        supports_realtime: true,
    },
    ModelEntry {
        id: "streaming-nemo-rnnt-en",
        display_name: "Streaming NeMo FastConformer RNN-T 480ms (English)",
        family: Family::Nemo,
        onnx_model_name: "csukuangfj/sherpa-onnx-nemo-streaming-fast-conformer-transducer-en-480ms",
        available_quantizations: &[""],
        param_count: 114_000_000,
        supports_realtime: true,
    },
    ModelEntry {
        id: "streaming-nemo-ctc-en-480ms",
        display_name: "Streaming NeMo FastConformer CTC 480ms (English)",
        family: Family::Nemo,
        onnx_model_name: "csukuangfj/sherpa-onnx-nemo-streaming-fast-conformer-ctc-en-480ms",
        available_quantizations: &[""],
        param_count: 114_000_000,
        supports_realtime: true,
    },
    ModelEntry {
        id: "streaming-nemo-ctc-en-1040ms",
        display_name: "Streaming NeMo FastConformer CTC 1040ms (English)",
        family: Family::Nemo,
        onnx_model_name: "csukuangfj/sherpa-onnx-nemo-streaming-fast-conformer-ctc-en-1040ms",
        available_quantizations: &[""],
        param_count: 114_000_000,
        supports_realtime: true,
    },
    ModelEntry {
        id: "streaming-nemo-ctc-en-80ms-int8",
        display_name: "Streaming NeMo FastConformer CTC (English)",
        family: Family::Nemo,
        onnx_model_name: "csukuangfj/sherpa-onnx-nemo-streaming-fast-conformer-ctc-en-80ms-int8",
        available_quantizations: &["int8"],
        param_count: 114_000_000,
        supports_realtime: true,
    },
    ModelEntry {
        id: "streaming-nemo-ctc-en-480ms-int8",
        display_name: "Streaming NeMo FastConformer CTC 480ms INT8 (English)",
        family: Family::Nemo,
        onnx_model_name: "csukuangfj/sherpa-onnx-nemo-streaming-fast-conformer-ctc-en-480ms-int8",
        available_quantizations: &["int8"],
        param_count: 114_000_000,
        supports_realtime: true,
    },
    ModelEntry {
        id: "streaming-nemo-ctc-en-1040ms-int8",
        display_name: "Streaming NeMo FastConformer CTC 1040ms INT8 (English)",
        family: Family::Nemo,
        onnx_model_name: "csukuangfj/sherpa-onnx-nemo-streaming-fast-conformer-ctc-en-1040ms-int8",
        available_quantizations: &["int8"],
        param_count: 114_000_000,
        supports_realtime: true,
    },
    ModelEntry {
        id: "streaming-nemo-rnnt-en-80ms",
        display_name: "Streaming NeMo FastConformer RNN-T 80ms (English)",
        family: Family::Nemo,
        onnx_model_name: "csukuangfj/sherpa-onnx-nemo-streaming-fast-conformer-transducer-en-80ms",
        available_quantizations: &[""],
        param_count: 114_000_000,
        supports_realtime: true,
    },
    ModelEntry {
        id: "streaming-nemo-rnnt-en-1040ms",
        display_name: "Streaming NeMo FastConformer RNN-T 1040ms (English)",
        family: Family::Nemo,
        onnx_model_name:
            "csukuangfj/sherpa-onnx-nemo-streaming-fast-conformer-transducer-en-1040ms",
        available_quantizations: &[""],
        param_count: 114_000_000,
        supports_realtime: true,
    },
    ModelEntry {
        id: "streaming-nemo-rnnt-en-80ms-int8",
        display_name: "Streaming NeMo FastConformer RNN-T (English)",
        family: Family::Nemo,
        onnx_model_name:
            "csukuangfj/sherpa-onnx-nemo-streaming-fast-conformer-transducer-en-80ms-int8",
        available_quantizations: &["int8"],
        param_count: 114_000_000,
        supports_realtime: true,
    },
    ModelEntry {
        id: "streaming-nemo-rnnt-en-480ms-int8",
        display_name: "Streaming NeMo FastConformer RNN-T 480ms INT8 (English)",
        family: Family::Nemo,
        onnx_model_name:
            "csukuangfj/sherpa-onnx-nemo-streaming-fast-conformer-transducer-en-480ms-int8",
        available_quantizations: &["int8"],
        param_count: 114_000_000,
        supports_realtime: true,
    },
    ModelEntry {
        id: "streaming-nemo-rnnt-en-1040ms-int8",
        display_name: "Streaming NeMo FastConformer RNN-T 1040ms INT8 (English)",
        family: Family::Nemo,
        onnx_model_name:
            "csukuangfj/sherpa-onnx-nemo-streaming-fast-conformer-transducer-en-1040ms-int8",
        available_quantizations: &["int8"],
        param_count: 114_000_000,
        supports_realtime: true,
    },
    ModelEntry {
        id: "streaming-parakeet-unified-en-240ms",
        display_name: "Streaming Parakeet Unified 240ms (English)",
        family: Family::Nemo,
        onnx_model_name: "csukuangfj2/sherpa-onnx-nemo-parakeet-unified-en-0.6b-streaming-240ms",
        available_quantizations: &[""],
        param_count: 600_000_000,
        supports_realtime: true,
    },
    ModelEntry {
        id: "streaming-parakeet-unified-en-560ms",
        display_name: "Streaming Parakeet Unified 560ms (English)",
        family: Family::Nemo,
        onnx_model_name: "csukuangfj2/sherpa-onnx-nemo-parakeet-unified-en-0.6b-streaming-560ms",
        available_quantizations: &[""],
        param_count: 600_000_000,
        supports_realtime: true,
    },
    ModelEntry {
        id: "streaming-parakeet-unified-en-1120ms",
        display_name: "Streaming Parakeet Unified 1120ms (English)",
        family: Family::Nemo,
        onnx_model_name: "csukuangfj2/sherpa-onnx-nemo-parakeet-unified-en-0.6b-streaming-1120ms",
        available_quantizations: &[""],
        param_count: 600_000_000,
        supports_realtime: true,
    },
    ModelEntry {
        id: "streaming-parakeet-unified-en-240ms-int8",
        display_name: "Streaming Parakeet Unified (English)",
        family: Family::Nemo,
        onnx_model_name:
            "csukuangfj2/sherpa-onnx-nemo-parakeet-unified-en-0.6b-int8-streaming-240ms",
        available_quantizations: &["int8"],
        param_count: 600_000_000,
        supports_realtime: true,
    },
    ModelEntry {
        id: "streaming-parakeet-unified-en-560ms-int8",
        display_name: "Streaming Parakeet Unified 560ms INT8 (English)",
        family: Family::Nemo,
        onnx_model_name:
            "csukuangfj2/sherpa-onnx-nemo-parakeet-unified-en-0.6b-int8-streaming-560ms",
        available_quantizations: &["int8"],
        param_count: 600_000_000,
        supports_realtime: true,
    },
    ModelEntry {
        id: "streaming-parakeet-unified-en-1120ms-int8",
        display_name: "Streaming Parakeet Unified 1120ms INT8 (English)",
        family: Family::Nemo,
        onnx_model_name:
            "csukuangfj2/sherpa-onnx-nemo-parakeet-unified-en-0.6b-int8-streaming-1120ms",
        available_quantizations: &["int8"],
        param_count: 600_000_000,
        supports_realtime: true,
    },
    ModelEntry {
        id: "streaming-nemotron-en-80ms",
        display_name: "Streaming Nemotron 80ms (English)",
        family: Family::Nemo,
        onnx_model_name:
            "csukuangfj2/sherpa-onnx-nemotron-speech-streaming-en-0.6b-80ms-2026-04-25",
        available_quantizations: &[""],
        param_count: 600_000_000,
        supports_realtime: true,
    },
    ModelEntry {
        id: "streaming-nemotron-en-160ms",
        display_name: "Streaming Nemotron 160ms (English)",
        family: Family::Nemo,
        onnx_model_name:
            "csukuangfj2/sherpa-onnx-nemotron-speech-streaming-en-0.6b-160ms-2026-04-25",
        available_quantizations: &[""],
        param_count: 600_000_000,
        supports_realtime: true,
    },
    ModelEntry {
        id: "streaming-nemotron-en-560ms",
        display_name: "Streaming Nemotron 560ms (English)",
        family: Family::Nemo,
        onnx_model_name:
            "csukuangfj2/sherpa-onnx-nemotron-speech-streaming-en-0.6b-560ms-2026-04-25",
        available_quantizations: &[""],
        param_count: 600_000_000,
        supports_realtime: true,
    },
    ModelEntry {
        id: "streaming-nemotron-en-1120ms",
        display_name: "Streaming Nemotron 1120ms (English)",
        family: Family::Nemo,
        onnx_model_name:
            "csukuangfj2/sherpa-onnx-nemotron-speech-streaming-en-0.6b-1120ms-2026-04-25",
        available_quantizations: &[""],
        param_count: 600_000_000,
        supports_realtime: true,
    },
    ModelEntry {
        id: "streaming-nemotron-en-80ms-int8",
        display_name: "Streaming Nemotron (English)",
        family: Family::Nemo,
        onnx_model_name:
            "csukuangfj2/sherpa-onnx-nemotron-speech-streaming-en-0.6b-80ms-int8-2026-04-25",
        available_quantizations: &["int8"],
        param_count: 600_000_000,
        supports_realtime: true,
    },
    ModelEntry {
        id: "streaming-nemotron-en-160ms-int8",
        display_name: "Streaming Nemotron 160ms INT8 (English)",
        family: Family::Nemo,
        onnx_model_name:
            "csukuangfj2/sherpa-onnx-nemotron-speech-streaming-en-0.6b-160ms-int8-2026-04-25",
        available_quantizations: &["int8"],
        param_count: 600_000_000,
        supports_realtime: true,
    },
    ModelEntry {
        id: "streaming-nemotron-en-560ms-int8",
        display_name: "Streaming Nemotron 560ms INT8 (English)",
        family: Family::Nemo,
        onnx_model_name:
            "csukuangfj2/sherpa-onnx-nemotron-speech-streaming-en-0.6b-560ms-int8-2026-04-25",
        available_quantizations: &["int8"],
        param_count: 600_000_000,
        supports_realtime: true,
    },
    ModelEntry {
        id: "streaming-nemotron-en-1120ms-int8",
        display_name: "Streaming Nemotron 1120ms INT8 (English)",
        family: Family::Nemo,
        onnx_model_name:
            "csukuangfj2/sherpa-onnx-nemotron-speech-streaming-en-0.6b-1120ms-int8-2026-04-25",
        available_quantizations: &["int8"],
        param_count: 600_000_000,
        supports_realtime: true,
    },
    ModelEntry {
        id: "nemo-canary-180m-flash",
        display_name: "NeMo Canary 180M Flash",
        family: Family::Nemo,
        onnx_model_name: "istupakov/canary-180m-flash-onnx",
        available_quantizations: &["", "int8"],
        param_count: 194_168_492,
        supports_realtime: true,
    },
    ModelEntry {
        id: "nemo-canary-1b-flash",
        display_name: "NeMo Canary 1B Flash",
        family: Family::Nemo,
        onnx_model_name: "istupakov/canary-1b-flash-onnx",
        available_quantizations: &["", "int8"],
        param_count: 883_000_000,
        supports_realtime: true,
    },
    ModelEntry {
        id: "nemo-fastconformer-ru-ctc",
        display_name: "NeMo FastConformer RU CTC",
        family: Family::Nemo,
        onnx_model_name: "nemo-fastconformer-ru-ctc",
        available_quantizations: &["", "int8"],
        param_count: 109_270_705,
        supports_realtime: true,
    },
    ModelEntry {
        id: "nemo-fastconformer-ru-rnnt",
        display_name: "NeMo FastConformer RU RNNT",
        family: Family::Nemo,
        onnx_model_name: "nemo-fastconformer-ru-rnnt",
        available_quantizations: &["", "int8"],
        param_count: 114_078_382,
        supports_realtime: true,
    },
    // ── GigaAM family (2) ────────────────────────────────────────────────────────────────
    ModelEntry {
        id: "gigaam-v3-e2e-ctc",
        display_name: "GigaAM v3 E2E CTC",
        family: Family::GigaAm,
        onnx_model_name: "gigaam-v3-e2e-ctc",
        available_quantizations: &["", "int8"],
        param_count: 243_000_000,
        supports_realtime: true,
    },
    ModelEntry {
        id: "gigaam-v3-e2e-rnnt",
        display_name: "GigaAM v3 E2E RNNT",
        family: Family::GigaAm,
        onnx_model_name: "gigaam-v3-e2e-rnnt",
        available_quantizations: &["", "int8"],
        param_count: 243_000_000,
        supports_realtime: true,
    },
    // ── Kaldi family (3) — Vosk + Zipformer ──────────────────────────────────────────────
    // NOTE: Kaldi/Vosk uses the `.` quant separator (`encoder.int8.onnx`) vs onnx-community's
    // `_` separator — handled in the model-cache / file-resolution slice, NOT here.
    ModelEntry {
        id: "alphacep/vosk-model-ru",
        display_name: "Vosk Russian",
        family: Family::Kaldi,
        onnx_model_name: "alphacep/vosk-model-ru",
        available_quantizations: &["", "int8"],
        param_count: 65_016_922,
        supports_realtime: true,
    },
    ModelEntry {
        id: "alphacep/vosk-model-small-ru",
        display_name: "Vosk Russian (Small)",
        family: Family::Kaldi,
        onnx_model_name: "alphacep/vosk-model-small-ru",
        available_quantizations: &["", "int8"],
        param_count: 22_986_644,
        supports_realtime: true,
    },
    ModelEntry {
        id: "zipformer-en",
        display_name: "Zipformer English",
        family: Family::Kaldi,
        onnx_model_name: "zipformer-en",
        available_quantizations: &[""],
        param_count: 70_000_000,
        supports_realtime: true,
    },
    // ── T-One family (1) ─────────────────────────────────────────────────────────────────
    ModelEntry {
        id: "t-tech/t-one",
        display_name: "T-One",
        family: Family::TOne,
        onnx_model_name: "t-tech/t-one",
        available_quantizations: &[""],
        param_count: 71_697_827,
        supports_realtime: true,
    },
    // ── Dolphin family (1) ───────────────────────────────────────────────────────────────
    ModelEntry {
        id: "dolphin-base-ctc",
        display_name: "Dolphin Base CTC",
        family: Family::Dolphin,
        onnx_model_name: "dolphin-base-ctc",
        // int8-only: Dolphin's default-export int8 graph is the only viable build (the fp32
        // default-export int8 DML segfaults — memory project_onnx_asr_single_source_of_truth).
        available_quantizations: &["int8"],
        param_count: 140_000_000,
        supports_realtime: true,
    },
];
