// AUTO-GENERATED by tools/generate-cloud-models.ts — DO NOT EDIT.
//
// Mirrors the AI SDK's internal transcription model-id unions so the cloud
// picker offers exactly what the installed providers can drive:
//   @ai-sdk/openai      → OpenAITranscriptionModelId
//   @ai-sdk/elevenlabs  → ElevenLabsTranscriptionModelId
//
// Re-run `bun generate` after bumping the @ai-sdk packages.

export const GENERATED_CLOUD_MODEL_IDS = {
	openai: [
		"whisper-1",
		"gpt-4o-mini-transcribe",
		"gpt-4o-transcribe",
	],
	elevenlabs: [
		"scribe_v1",
		"scribe_v1_experimental",
	],
} as const;
